plugins:
  patreon_enabled:
    default: false
  patreon_login_enabled:
    default: false
    client: true
  patreon_client_id:
    default: ''
  patreon_client_secret:
    default: ''
  patreon_webhook_secret:
    default: ''
  patreon_creator_access_token:
    default: ''
  patreon_creator_refresh_token:
    default: ''
  patreon_declined_pledges_grace_period_days:
    default: 7
  max_patreon_api_reqs_per_hr:
    default: 20
  max_patreon_api_reqs_per_day:
    default: 200
