plugins:
  patreon_enabled:
    default: false
  patreon_login_enabled:
    default: false
    client: true
  patreon_client_id:
    default: ''
  patreon_client_secret:
    default: ''
  patreon_webhook_secret:
    default: ''
  patreon_creator_access_token:
    default: ''
  patreon_creator_refresh_token:
    default: ''
